### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by SmaDababaXor** [aeiousy/Kei#1]
hello thanks for making the bot a open source and i appreiciate the bot but it says this error and im new to dev so please if you have time reply to me 

/home/runner/Kei/index.js:23
client.database?.init();
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by aeiousy** [comment]
If your running it on repl.it I recommend running it on glitch because repl.it cannot connect to mongodb database or if you have a pc download the file and extract it and run it using npm start or node . After filling in you .env file

**Comment by SmaDababaXor** [comment]
i used both downloading and using repl.it both have the same issue plz help

**Comment by aeiousy** [comment]
If you can’t run it on glitch nor repl.it you will need to install it on your pc

**Comment by SmaDababaXor** [comment]
thx it works now
